In [2]:
import os
import pandas as pd
from IPython.display import display

path = os.path.expanduser("~/Desktop/community resiliance/data/a143145.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)

print("\nColumns list:", df.columns.tolist(), "\n")
display(df.head(20))

Rows, Columns: (1000, 12)

Columns list: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'choose_one', 'choose_one:confidence', 'choose_one_gold', 'nil', 'text_no_rt', 'tweet', 'user']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,nil,text_no_rt,tweet,user
0,221934923,True,golden,3,11/13/12 2:06,Personal Only,1.0000,Personal Only,NaN,......................Ã¤Ã³Ã¬@Brains_x_Beauty: ...,RT @TheHolyKaron: ......................Ã¤Ã³Ã¬...,____DatPMF
1,221934924,True,golden,2,11/13/12 2:16,Informative (Indirect),0.5150,Informative (Indirect),NaN,At least 39 dead millions without power in San...,At least 39 dead millions without power in San...,_3091004140882
2,221934925,True,golden,2,11/13/12 2:06,Personal Only,1.0000,Personal Only,NaN,Clearly no one wants to look good for sandy la...,Clearly no one wants to look good for sandy la...,_JordanDawn_
3,221934926,True,golden,1,11/11/12 1:44,Other,1.0000,Informative (Indirect),NaN,Hurricane #Sandy hits the Statue Of Liberty ht...,RT @ImJay_wbu: Hurricane #Sandy hits the Statu...,_k4typerry
4,221934927,False,finalized,3,11/10/12 12:38,Informative (Indirect),1.0000,NaN,NaN,Watch Hurricane #Sandy prowling the East Coast...,RT @NASA: Watch Hurricane #Sandy prowling the ...,_KieranJD_
5,221934928,True,golden,2,11/13/12 2:16,Personal Only,1.0000,Informative (Direct),NaN,Hurricane Sandy Calming Down .. I guess she G...,RT @BreonnaJ: Hurricane Sandy Calming Down .....,_LEFT_BRAIN
6,221934929,False,finalized,3,11/13/12 1:35,Informative (Indirect),1.0000,NaN,NaN,President Obama declares states of emergency i...,RT @cnnbrk: President Obama declares states of...,_LetsFlyAway_
7,221934930,True,golden,2,11/13/12 2:07,Personal Only,1.0000,Personal Only,NaN,We thought sandy wasn't shit that shit destroy...,We thought sandy wasn't shit that shit destroy...,_lovekiaraa
8,221934931,True,golden,17,11/13/12 1:57,Informative (Direct),0.4100,Informative (Direct),NaN,Not only NY...Ã¤Ã³Ã¬@CNN_Oppmann: When I left ...,Not only NY...Ã¤Ã³Ã¬@CNN_Oppmann: When I left ...,_s_usan
9,221934932,True,golden,46,11/13/12 3:15,Personal Only,0.8759,Personal Only,NaN,If my license test gets cancelled because of s...,If my license test gets cancelled because of s...,_saywhut
10,221934933,True,golden,22,11/13/12 1:58,Personal Only,0.5566,Personal Only,NaN,realshit #sandy my niggah skip nyc its all bou...,realshit #sandy my niggah skip nyc its all bou...,_YungMonroe
11,221934934,True,golden,46,11/13/12 1:56,Personal Only,0.7052,Personal Only,NaN,#Sandy needs to chill out,#Sandy needs to chill out,007toytoy
12,221934935,True,golden,18,11/13/12 2:05,Informative (Indirect),0.8704,Informative (Indirect),NaN,NJ Guard delivers food to trapped Hoboken resi...,NJ Guard delivers food to trapped Hoboken resi...,00ASHLEYMARIE00
13,221934936,True,golden,13,11/13/12 1:54,Informative (Indirect),0.4004,Informative (Direct)\nInformative (Indirect)\n...,NaN,Awesome. Go NYC. RT @pourmecoffee: Empire Stat...,RT @DaphneUn: Awesome. Go NYC. RT @pourmecoffe...,0odin
14,221934937,True,golden,13,11/13/12 1:36,Informative (Indirect),0.6165,Personal Only,NaN,"Former FEMA Director """"Brownie"""" criticizes Ob...","Former FEMA Director ""Brownie"" criticizes Obam...",100yearsofmovie
15,221934938,True,golden,62,11/13/12 3:15,Personal Only,0.5682,Other,NaN,So I can offer you #sandy victims some coffee....,RT @JustAmberMFC: So I can offer you #sandy vi...,12345clumsy6789
16,221934939,True,golden,31,11/12/12 5:39,Informative (Direct or Indirect),0.3541,Informative (Direct or Indirect),NaN,28 deaths due to Hurricane Sandy | Charlotte t...,RT @HenderGrande: 28 deaths due to Hurricane S...,1EmmaHenderson
17,221934940,True,golden,51,11/13/12 1:55,Informative (Indirect),0.7918,Informative (Indirect),NaN,NYC's Bellevue Hospital Set to Evacuate - ABC ...,NYC's Bellevue Hospital Set to Evacuate - ABC ...,1sthealthnews
18,221934941,True,golden,23,11/11/12 19:43,Informative (Indirect),0.6415,Other,NaN,Fox News mocks science gives airtime to climat...,RT @thinkprogress: Fox News mocks science give...,2dialogue
19,221934942,True,golden,12,11/11/12 19:44,Informative (Indirect),0.6217,Informative (Indirect),NaN,"this is ironic given comments by certain """"pas...","this is ironic given comments by certain ""past...",30ftspirit

In [3]:
import os
import pandas as pd
from IPython.display import display

path = os.path.expanduser("~/Desktop/community resiliance/data/a144267.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)



print("\nColumns list:", df.columns.tolist(), "\n")
display(df.head(20))

Rows, Columns: (543, 12)

Columns list: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'choose_one', 'choose_one:confidence', 'choose_one_gold', 'text_no_rt', 'tweet', 'type', 'user']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,text_no_rt,tweet,type,user
0,223607030,False,finalized,3,11/14/2012 03:26:51,Casualties and damage,1.0000,NaN,28 deaths due to Hurricane Sandy | Charlotte t...,RT @HenderGrande: 28 deaths due to Hurricane S...,Informative (Direct or Indirect),1EmmaHenderson
1,223607031,True,golden,3,11/14/2012 03:41:27,Casualties and damage,1.0000,Casualties and damage,Sandy kills 50 people nationwide 18 were New Y...,Sandy kills 50 people nationwide 18 were New Y...,Informative (Direct or Indirect),9NEWS
2,223607032,False,finalized,3,11/14/2012 03:38:40,Casualties and damage,0.6849,NaN,RT @nowthised: Wider shot of scaffolding toppl...,RT @twc_hurricane: RT @nowthised: Wider shot o...,Informative (Direct or Indirect),AbrahamAkiva
3,223607033,True,golden,10,11/14/2012 03:35:39,Caution and advice,0.8900,Caution and advice,#Sandy will be onshore about 6pm. Slightly fas...,RT @growingwisdom: #Sandy will be onshore abou...,Informative (Direct or Indirect),aecheylon
4,223607034,True,golden,7,11/14/2012 03:36:35,"Donations of money, goods or services",0.5727,"Donations of money, goods or services",@ChrisFRC lost startups can go to @AlleyNYC. T...,@ChrisFRC lost startups can go to @AlleyNYC. T...,Informative (Direct or Indirect),AHolidayiii
5,223607035,True,golden,9,11/14/2012 03:26:01,Casualties and damage,1.0000,Casualties and damage,Sandy death toll climbs; millions remain witho...,Sandy death toll climbs; millions remain witho...,Informative (Direct or Indirect),alexandermimi
6,223607036,True,golden,3,11/14/2012 03:42:00,Casualties and damage,1.0000,Casualties and damage,Extensive flooding in all subway tunnels says ...,RT @emmagkeller: Extensive flooding in all sub...,Informative (Direct or Indirect),alischaw
7,223607037,True,golden,10,11/14/2012 03:35:39,"Donations of money, goods or services",1.0000,"Donations of money, goods or services",400 Volunteers are needed for areas that took ...,400 Volunteers are needed for areas that took ...,Informative (Direct or Indirect),AmandaBlount
8,223607038,True,golden,9,11/14/2012 03:31:53,Caution and advice,0.8735,Caution and advice,Storm just now hitting Jersey...Milford is fee...,Storm just now hitting Jersey...Milford is fee...,Informative (Direct or Indirect),beball
9,223607039,True,golden,10,11/14/2012 03:25:45,Caution and advice,0.6982,Caution and advice,City Public Schools will be closed Wednesday 1...,RT @ChrisCQuinn: City Public Schools will be c...,Informative (Direct or Indirect),BrandingWorld
10,223607040,True,golden,5,11/14/2012 03:38:01,Information Source,0.4343,Caution and advice,checked the news. yes there is schol tomoro. s...,checked the news. yes there is schol tomoro. s...,Informative (Direct or Indirect),BrandoCummando
11,223607041,True,golden,10,11/14/2012 03:33:59,Caution and advice,0.5830,Caution and advice,Hurricane Sandy is going to fill the subways w...,RT @JessieWessie33: Hurricane Sandy is going t...,Informative (Direct or Indirect),britthanus
12,223607042,True,golden,6,11/14/2012 03:38:40,Caution and advice,0.4721,Caution and advice,Omg NYC is now impacted by hurricane #Sandy,Omg NYC is now impacted by hurricane #Sandy,Informative (Direct or Indirect),BuniYani
13,223607043,True,golden,11,11/14/2012 03:33:59,Casualties and damage,0.8990,Casualties and damage,40 people killed during Super Storm Sandy! Don...,40 people killed during Super Storm Sandy! Don...,Informative (Direct or Indirect),CalumWilcock
14,223607044,True,golden,11,11/14/2012 03:33:59,Unknown,0.7170,Unknown,Due to Hurricane #Sandy the @90210 episode is ...,RT @ryanlochte: Due to Hurricane #Sandy the @9...,Informative (Direct or Indirect),chuue
15,223607045,True,golden,11,11/14/2012 03:34:01,Unknown,0.6308,Unknown,they just showed a dude on a Jet Ski off of Ba...,they just showed a dude on a Jet Ski off of Ba...,Informative (Direct or Indirect),codyjmorton
16,223607046,True,golden,11,11/14/2012 03:30:21,Casualties and damage,0.7985,Casualties and damage,+++BREAKING+++ New Jersey sewage plant hit by ...,+++BREAKING+++ New Jersey sewage plant hit by ...,Informative (Direct or Indirect),couchpotato_es2
17,223607047,True,golden,12,11/14/2012 03:18:55,Caution and advice,0.8484,Caution and advice,NYC ALERT: All pets are accepted on the subway...,RT @ASPCA: NYC ALERT: All pets are accepted on...,Informative (Direct or Indirect),CourtThornton1
18,223607048,True,golden,12,11/14/2012 03:31:53,Casualties and damage,0.5785,Casualties and damage,A boat lies across the railroad tracks near Me...,RT @aadragna: A boat lies across the railroad ...,Informative (Direct or Indirect),CrawfordRainaL
19,223607049,True,golden,10,11/14/2012 03:30:52,Casualties and damage,0.8883,Casualties and damage,We are worried about the #UN documents histori...,RT @UNLibrary: We are worried about the #UN do...,Informative (Direct or Indirect),Danzig661

In [4]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/a146274.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(20))

Rows, Columns: (70, 17)
Columns: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'type_of_message', 'type_of_message:confidence', 'url_or_name_of_the_stationchannel', 'what', 'category', 'text_no_rt', 'tweet', 'type', 'type_of_message_gold', 'url_or_name_of_the_stationchannel_gold', 'user', 'what_gold']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,type_of_message,type_of_message:confidence,url_or_name_of_the_stationchannel,what,category,text_no_rt,tweet,type,type_of_message_gold,url_or_name_of_the_stationchannel_gold,user,what_gold
0,227174029,True,golden,7,11/25/2012 07:05:36,None of the above,0.8817,N/A\nn/a\nN/A\nN/A\nNA\nN/A\nN/A,sandy was a weak ass bitch\nsandy was a weak a...,Informative (Direct or Indirect),checked the news. yes there is schol tomoro. s...,checked the news. yes there is schol tomoro. s...,Information Source,None of the above,NaN,BrandoCummando,NaN
1,227174030,True,golden,5,11/25/2012 07:13:17,Look at this photo or these photos,0.4002,http://t.co/j6I531we\nhttp://t.co/j6I531we\nN/...,Hurricane #Sandy hits NYC hard with intense wi...,Informative (Direct or Indirect),Hurricane #Sandy hits NYC hard with intense wi...,Hurricane #Sandy hits NYC hard with intense wi...,Information Source,Look at this photo or these photos\nNone of th...,http://t.co/j6I531we,davidfig79,NaN
2,227174031,True,golden,6,11/24/2012 04:04:24,None of the above,0.6951,n/a\nN/A\nN/A\nN/A\nN/A\nN/A,press conference LIVE now on #Sandy aftermath....,Informative (Direct or Indirect),Mayor Bloomberg holding press conference LIVE ...,RT @HuffingtonPost: Mayor Bloomberg holding pr...,Information Source,None of the above,NaN,HurricSandyNews,NaN
3,227174032,True,golden,1,11/24/2012 22:17:12,Look at this video or these videos,1.0000,http://t.co/eofIJ7Fe,Statue of Liberty,Informative (Direct or Indirect),RT @mrspantsworth: Statue of Liberty Torchcam ...,RT @dirtymondaze: RT @mrspantsworth: Statue of...,Information Source,Look at this web site/page,http://t.co/eofIJ7Fe,loloster,some idea of the force of #sandy
4,227174033,True,golden,2,11/23/2012 02:49:17,Look at this web site/page,0.5455,http://t.co/eCGqw1ek\nhttp://t.co/eCGqw1ek,images from the empty #NYC subways\nfrom the e...,Informative (Direct),even the rats left town RT @YGNw: Eery images ...,even the rats left town RT @YGNw: Eery images ...,Information Source,Look at this photo or these photos,http://t.co/eCGqw1ek,dc_fusion,Eery images from the empty #NYC subways
5,227174034,True,golden,7,11/25/2012 07:09:18,None of the above,1.0000,N/A\nn/a\nN/A\nN/A\nN/A\nN/A\nN/A,BEST LIVE updates on the unfolding Hurricane S...,Informative (Direct),BEST LIVE updates on the unfolding Hurricane S...,BEST LIVE updates on the unfolding Hurricane S...,Information Source,None of the above,NaN,DowagerDuchessR,NaN
6,227174035,True,golden,5,11/24/2012 14:30:06,Look at this photo or these photos,1.0000,http://t.co/09U9L5rW\nhttp://t.co/09U9L5rW\nht...,Photos of the unbelievable scenes left in #Hur...,Informative (Direct),Photos of the unbelievable scenes left in #Hur...,RT @NBCNewsPictures: Photos of the unbelievabl...,Information Source,Look at this photo or these photos,http://t.co/09U9L5rW,Englishmuffin10,unbelievable scenes left in #Hurricane #Sandy'...
7,227174036,True,golden,3,11/24/2012 22:17:12,Look at this web site/page,0.7237,http://t.co/DkPjVctS\nhttp://t.co/DkPjVctS\nht...,An inside look at NYU hospital's near disaster...,Informative (Direct),An inside look at NYU hospital's near disaster...,RT @CBSThisMorning: An inside look at NYU hosp...,Information Source,Look at this video or these videos,http://t.co/DkPjVctS,joeperrone,inside look at NYU hospital
8,227174037,True,golden,3,11/23/2012 18:20:00,Look at this photo or these photos,1.0000,http://t.co/MiGmwQRs\nhttp://t.co/MiGmwQRs\nht...,Possibly one of the most amazing things I've e...,Informative (Direct),Possibly one of the most amazing things I've e...,RT @RichR11: Possibly one of the most amazing ...,Information Source,Look at this photo or these photos,http://t.co/MiGmwQRs,KMertzzz,TombOfTheUnknownSoldier
9,227174038,True,golden,2,11/24/2012 22:35:28,Look at this photo or these photos,1.0000,http://t.co/wd2zww1M\nhttp://t.co/wd2zww1M,Real time instagram pics of the #Sandy happeni...,Informative (Direct),Real time instagram pics of the #Sandy happeni...,Real time instagram pics of the #Sandy happeni...,Information Source,Look at this photo or these photos,http://t.co/wd2zww1M,Lolakakon,pics of the #Sandy happenings\nReal time insta...
10,227174039,True,golden,5,11/25/2012 07:05:36,Look at this video or these videos,1.0000,http://t.co/kRWlHaXN\nhttp://t.co/kRWlHaXN\nht...,Hurricane Sandy | Kill Confirmed\nHurricane Sa...,Informative (Direct),I uploaded a @YouTube video http://t.co/kRWlHa...,I uploaded a @YouTube video http://t.co/kRWlHa...,Information Source,Look at this video or these videos,http://t.co/kRWlHaXN MW3,PyroXL,Hurricane Sandy
11,227174040,True,golden,5,11/24/2012 14:25:36,Look at this photo or these photos,0.8060,http://t.co/hpANdaW2\nhttp://t.co/hpANdaW2\nht...,This is by far one of the most ominous shots f...,Informative (Direct),This is by far one of the most ominous shots f...,This is by far one of the most ominous shots f...,Information Source,Look at this photo or these photos,http://t.co/hpANdaW2,TheToddHarris,one of the most ominous shots from NYC
12,227174041,True,golden,2,11/23/2012 16:11:21,Look at this video or these videos,1.0000,http://t.co/4C78dm5H\nhttp://t.co/4C78dm5H,Watch Hurricane #Sandy prowling the East Coast...,Informative (Indirect),Watch Hurricane #Sandy prowling the East Coast...,RT @NASA: Watch Hurricane #Sandy prowling the ...,Information Source,Look at this video or these videos,http://t.co/4C78dm5H,_KieranJD_,Hurricane #Sandy prowling the East Coast
13,227174042,True,golden,5,11/25/2012 07:05:36,Watch this TV channel (or: I am watching this ...,0.3538,http://t.co/H9FXzHLQ\nhttp://t.co/H9FXzHLQ\nNA...,US President @barackobama arrives\nbarackobama...,Informative (Indirect),LIVE: US President @barackobama arrives in Atl...,RT @BBCBreaking: LIVE: US President @barackoba...,Information Source,Look at this video or these videos,http://t.co/H9FXzHLQ\nhttp://www.bbc.co.uk/ne...,AllisonGolds,@barackobama arrives in Atlantic City New Jers...
14,227174043,True,golden,4,11/25/2012 07:09:18,Look at this photo or these photos,1.0000,http://t.co/1UE9LQWw\nhttp://t.co/1UE9LQWw\nht...,Pictures: Recovery starts after deadly storm S...,Informative (Indirect),In Pictures: Recovery starts after deadly stor...,In Pictures: Recovery starts after deadly stor...,Information Source,Look at this photo or these photos,http://t.co/1UE9LQWw,anummedia,Recovery starts after deadly storm
15,227174044,True,golden,2,11/24/2012 22:17:12,Look at this web site/page,0.5882,http://t.co/AyEyfY4k\nhttp://t.co/AyEyfY4k,Hurricane Sandy Aftermath\nHurricane Sandy Aft...,Informative (Indirect),Photos: The Hurricane Sandy Aftermath: She cam...,RT @FLH57: Photos: The Hurricane Sandy Afterma...,Information Source,Look at this photo or these photos,http://t.co/AyEyfY4k,arundevkr,Hurricane Sandy Aftermath
16,227174046,True,golden,6,11/24/2012 22:10:58,Look at this photo or these photos,1.0000,http://t.co/RyS0MRH5\nhttp://t.co/RyS0MRH5\nht...,tanker was washed onto Staten Island's shore b...,Informative (Indirect),This tanker was washed onto Staten Island's sh...,RT @HuffingtonPost: This tanker was washed ont...,Information Source,Look at this photo or these photos,http://t.co/RyS0MRH5 / http://t.co/FXYaYjIb,bianca_lutai,tanker was washed onto Staten Island's shore
17,227174047,True,golden,6,11/25/2012 07:09:18,None of the above,0.8236,N/A\nN/A\nN/A\nN/A\nN/A\nN/A,Governor to give #Sandy briefing at 11:15am\nG...,Informative (Indirect),BREAKING: Governor to give #Sandy briefing at ...,RT @NYGovCuomo: BREAKING: Governor to give #Sa...,Information Source,None of the above,NaN,CapitalTonight,NaN
18,227174048,True,golden,6,11/24/2012 22:17:12,Look at this photo or these photos,1.0000,http://t.co/r25PQ3lT\nhttp://t.co/r25PQ3lT\nht...,Tomb of the Unknown Soldier\nTomb of the Unkno...,Informative (Indirect),Sandy Pic: Tomb of the Unknown Soldier http://...,Sandy Pic: Tomb of the Unknown Soldier http://...,Information Source,Look at this photo or these photos,http://t.co/r25PQ3lT,ChrisMader30,Tomb of the Unknown Soldier
19,227174049,True,golden,9,11/25/2012 07:05:36,Look at this photo or these photos,0.8711,http://t.co/ZYbZo5Re\nhttp://t.co/ZYbZo5Re\nht...,Statue of Liberty preps for the arrival of #Sa...,Informative (Indirect),Statue of Liberty preps for the arrival of #Sa...,Statue of Liberty preps for the arrival of #Sa...,Information Source,Look at this photo or these photos,http://t.co/ZYbZo5Re,ChuckyT3,Statue of Liberty

In [5]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/a146281.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(20))

Rows, Columns: (170, 17)
Columns: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'hom_many_injured_or_dead_if_people', 'people_or_infrastructure', 'people_or_infrastructure:confidence', 'what_infrastructure_was_damaged_if_infrastructure', 'category', 'hom_many_injured_or_dead_if_people_gold', 'people_or_infrastructure_gold', 'text_no_rt', 'tweet', 'type', 'user', 'what_infrastructure_was_damaged_if_infrastructure_gold']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,hom_many_injured_or_dead_if_people,people_or_infrastructure,people_or_infrastructure:confidence,what_infrastructure_was_damaged_if_infrastructure,category,hom_many_injured_or_dead_if_people_gold,people_or_infrastructure_gold,text_no_rt,tweet,type,user,what_infrastructure_was_damaged_if_infrastructure_gold
0,227175113,True,golden,12,11/23/2012 14:36:01,28\n28\n28\n28\n28\n28\n28\n28\n28\n28\n28\n28,People: dead,1.0000,\n\n\n\n\n\n\n\n\n\n\n,Informative (Direct or Indirect),28,People: dead,28 deaths due to Hurricane Sandy | Charlotte t...,RT @HenderGrande: 28 deaths due to Hurricane S...,Casualties and damage,1EmmaHenderson,NaN
1,227175114,True,golden,12,11/23/2012 13:13:34,50\n50\n50\n50 people nationwide 18 were New Y...,Both people and infrastructure,0.7143,homes\n\n8 million homes\n8 million homes stil...,Informative (Direct or Indirect),50\nkills 50 people nationwide\n50 people nati...,People: dead\nBoth people and infrastructure,Sandy kills 50 people nationwide 18 were New Y...,Sandy kills 50 people nationwide 18 were New Y...,Casualties and damage,9NEWS,8 million homes still without power\n8 millio...
2,227175115,True,golden,7,11/23/2012 09:09:19,\n\n\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",0.5353,\nscaffolding toppling car\nshot of scaffoldin...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",RT @nowthised: Wider shot of scaffolding toppl...,RT @twc_hurricane: RT @nowthised: Wider shot o...,Casualties and damage,AbrahamAkiva,scaffolding toppling car\nshot of scaffolding ...
3,227175116,True,golden,11,11/23/2012 13:20:51,\n\n\n\nnone\n\ntoll climbs\n\n\n\ntoll climbs,Both people and infrastructure,0.5651,"homes\npower, homes\nThousands of homes\nhomes...",Informative (Direct or Indirect),N/A\nN/a,Both people and infrastructure,Sandy death toll climbs; millions remain witho...,Sandy death toll climbs; millions remain witho...,Casualties and damage,alexandermimi,millions remain without power = electricity da...
4,227175117,True,golden,15,11/23/2012 14:25:53,\n\n\n\n\n\n\n\n\n\n\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",1.0000,Extensive flooding in all subway tunnels\nExte...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",Extensive flooding in all subway tunnels says ...,RT @emmagkeller: Extensive flooding in all sub...,Casualties and damage,alischaw,all subway tunnels\nExtensive flooding in all ...
5,227175118,True,golden,12,11/23/2012 13:59:20,40\n40\n40 people\n40\n40\n40\n40\n40\n40\n46\...,People: dead,1.0000,\n\n\n\n\n\n\n\n\n\n\n,Informative (Direct or Indirect),40,People: dead,40 people killed during Super Storm Sandy! Don...,40 people killed during Super Storm Sandy! Don...,Casualties and damage,CalumWilcock,NaN
6,227175119,True,golden,9,11/23/2012 14:15:54,\n\n\n\n\n\nNew Jersey sewage plant hit\n\n,"Infrastructure (building, bridge, road, etc.) ...",1.0000,sewage plant\nsewage plant\nNew Jersey sewage ...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",+++BREAKING+++ New Jersey sewage plant hit by ...,+++BREAKING+++ New Jersey sewage plant hit by ...,Casualties and damage,couchpotato_es2,sewage plant
7,227175120,True,golden,10,11/23/2012 14:38:49,\n\n\n\n\n\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",0.6308,\nboat\nMetro-North's Ossining station\n\nboat...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",A boat lies across the railroad tracks near Me...,RT @aadragna: A boat lies across the railroad ...,Casualties and damage,CrawfordRainaL,boat
8,227175121,True,golden,8,11/23/2012 13:20:51,\n\nnone\n\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",0.7965,\n\nUN documents historical collections\nUN do...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",We are worried about the #UN documents histori...,RT @UNLibrary: We are worried about the #UN do...,Casualties and damage,Danzig661,UN documents historical collection\nhistorical...
9,227175122,False,golden,3,11/22/2012 17:56:56,\n\n,"Infrastructure (building, bridge, road, etc.) ...",1.0000,the aquarium building itself is fine\naquarium...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",@leeannderthol No the aquarium building itself...,@leeannderthol No the aquarium building itself...,Casualties and damage,djramone13,aquarium building
10,227175123,True,golden,9,11/23/2012 14:19:51,\n\nnone\n\n\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",1.0000,building\ncollapsed crane dangling from a buil...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",NYC firefighters look up at a collapsed crane ...,RT @TIME: NYC firefighters look up at a collap...,Casualties and damage,dominicdileo,crane
11,227175124,False,golden,6,11/22/2012 16:31:26,\n0\n\n\n\n,"Infrastructure (building, bridge, road, etc.) ...",0.3719,\n\npower\n\nWeston Without Power\nWithout Power,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",Nearly All Of Weston Without Power After Hurri...,Nearly All Of Weston Without Power After Hurri...,Casualties and damage,EastonDV,Power\nWeston Without Power\nWeston\nWithout P...
12,227175125,True,golden,10,11/23/2012 13:55:34,94\n94\n94\n94\n94\n94\n94\n94\n94\n94,People: dead,0.9098,\n\n\n\n\n\n\n\nhomes and the New York subway ...,Informative (Direct or Indirect),94,People: dead,Latest death toll from #Sandy is 94 overall in...,RT @cnnbrk: Latest death toll from #Sandy is 9...,Casualties and damage,GabrielaNicole_,NaN
13,227175126,False,golden,6,11/22/2012 17:52:42,\n\n\n\n\n,Not damage-related,0.8321,\n\n\n\n\n,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",The four zoos in NYC say not a single animal w...,RT @gma: The four zoos in NYC say not a single...,Casualties and damage,gfreeislife,zoos
14,227175127,True,golden,3,11/23/2012 15:16:59,"2, 1, 1, 1, 5\n2 deaths in New Jersey 1 in Con...",People: dead,1.0000,\n\n,Informative (Direct or Indirect),"2, 1, 1, 1, 5",People: dead,2 deaths in New Jersey 1 in Connecticut 1 in W...,RT @GoogleFacts: 2 deaths in New Jersey 1 in C...,Casualties and damage,hassan_io,NaN
15,227175128,True,golden,9,11/23/2012 14:36:01,\n\n\n\n\n\n\nSandy fury\nN/A,People: dead,0.8955,\n\n\n\n\n\n\n\n,Informative (Direct or Indirect),NaN,People: dead,Sandy fury kills in NY. Hmm balasan tuhan kot ...,RT @maiymartiny: Sandy fury kills in NY. Hmm b...,Casualties and damage,husnajer,NaN
16,227175129,True,golden,14,11/23/2012 14:36:01,\n\n\n\n\n\n\n\n\n\n\n\n\n,Not specified (maybe people or infrastructure),0.3713,Sandy casualty #frankenstorm #nyc #westvillage...,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",Sandy casualty #frankenstorm #nyc #westvillage...,Sandy casualty #frankenstorm #nyc #westvillage...,Casualties and damage,J_Hubbell,NaN
17,227175130,False,golden,4,11/23/2012 14:21:26,7588\n7588\n7588\n7588,People: dead,1.0000,\n\n\n,Informative (Direct or Indirect),7588 \n7588 deaths 604045 cases\n7588 deaths 6...,People: dead,#Cholera update 10/19: 7588 deaths 604045 case...,#Cholera update 10/19: 7588 deaths 604045 case...,Casualties and damage,JakobJohnston,Cholera\ndeaths
18,227175131,True,golden,10,11/23/2012 13:43:14,\n\n\n\n\n\n\n\n\n,Not damage-related,0.5069,FEMA\n\n\n\n\n\n\n\nFEMA stands\n,Informative (Direct or Indirect),NaN,Not damage-related,If #Sandy causes major damage FEMA stands read...,RT @JohnFugelsang: If #Sandy causes major dama...,Casualties and damage,Jetsetter23,NaN
19,227175132,True,golden,8,11/23/2012 14:22:55,\n\n\n\n\n\n\n,Not damage-related,0.6751,building\nEmpire State Building\n\n\n\n\n\n,Informative (Direct or Indirect),NaN,"Infrastructure (building, bridge, road, etc.) ...",This is...unreal. Essentially the only buildin...,RT @JustinKing224: This is...unreal. Essential...,Casualties and damage,Killamop,power

In [6]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/a146283.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(20))

Rows, Columns: (126, 21)
Columns: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'source', 'type_of_advice_or_caution', 'type_of_advice_or_caution:confidence', 'what', 'when', 'where', 'category', 'source_gold', 'text_no_rt', 'tweet', 'type', 'type_of_advice_or_caution_gold', 'user', 'what_gold', 'when_gold', 'where_gold']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,source,type_of_advice_or_caution,type_of_advice_or_caution:confidence,what,when,...,category,source_gold,text_no_rt,tweet,type,type_of_advice_or_caution_gold,user,what_gold,when_gold,where_gold
0,227175857,True,golden,8,12/8/2012 19:09:26,#sandy\nN/A\nN/A\nn/a\nN/A\n\nN/A\nn/a,A hurricane sighting has been reported,0.7629,Storm just now hitting Jersey\nAll bridges clo...,now\nnow\njust now\nn/a\nN/A\nnow\nnow\njust now,...,Informative (Direct or Indirect),NaN,Storm just now hitting Jersey...Milford is fee...,Storm just now hitting Jersey...Milford is fee...,Caution and advice,A hurricane sighting has been reported,beball,hitting Jersey\nAll bridges closing in NYC & J...,now,NYC\nJersey\nJersey\nNYC & Jersey
1,227175859,False,golden,1,11/25/2012 17:31:06,NaN,Other,1.0000,Hurricane Sandy is going to fill the subways w...,NaN,...,Informative (Direct or Indirect),NaN,Hurricane Sandy is going to fill the subways w...,RT @JessieWessie33: Hurricane Sandy is going t...,Caution and advice,Other,britthanus,fill the subways with water,NaN,NYC
2,227175860,True,golden,34,12/10/2012 06:05:12,\nn/a\n\n#Sandy\nn/a\nn/a\n#Sandy\n#Sandy\n\n\...,A hurricane sighting has been reported,0.7427,NYC is now impacted by hurricane\nimpacted\nhu...,now\nnow\n\nnow\nn/a\nn/a\nN/A\nnow\n\nnow\nno...,...,Informative (Direct or Indirect),NaN,Omg NYC is now impacted by hurricane #Sandy,Omg NYC is now impacted by hurricane #Sandy,Caution and advice,A hurricane sighting has been reported,BuniYani,Impacted\nNYC is now impacted by hurricane\nim...,Now,NYC\nNYC
3,227175862,True,golden,31,12/10/2012 06:08:53,n/a\n\n#Sandy\n#Sandy\nN/A\n\n\n\n\nN/A\n\nN/A...,Other,0.9531,stock market closing\nstock market closing for...,n/a\n\nna\nN/A\nN/A\n\n1988\n\n\nN/A\n\nN/A\ns...,...,Informative (Direct or Indirect),NaN,First time since 1888 stock market closing for...,First time since 1888 stock market closing for...,Caution and advice,Other,feverplay_xo,stock market closing\nstock market closing for...,N/A\nn/a,N/A\nn/a
4,227175867,False,golden,1,11/25/2012 17:24:06,NaN,A hurricane sighting has been reported,1.0000,Hurricane Sandy,NaN,...,Informative (Direct or Indirect),NaN,Hurricane Sandy or else Frankestorm heading to...,RT @KateNinaA: Hurricane Sandy or else Frankes...,Caution and advice,A hurricane sighting has been reported\nOther,LuciiAgudo,Hurricane Sandy or else Frankestorm,NaN,heading toward NYC
5,227175868,False,golden,1,11/25/2012 17:17:44,NaN,Other,1.0000,NYC closing bridges and tunnels,at 7pm,...,Informative (Direct or Indirect),NaN,NYC closing bridges and tunnels at 7pm #Sandy,NYC closing bridges and tunnels at 7pm #Sandy,Caution and advice,Other,MikeBeam,NYC closing bridges and tunnels,at 7pm,NaN
6,227175869,True,golden,22,12/10/2012 06:12:57,#Sandy\nn/a\n#Sandy\nN/A\n\n\nN/A\nN/A\n\n\nn/...,Other,1.0000,water coming out of your faucet\nwater\nwater ...,na\nn/a\nN/A\nN/A\n\n\nN/A\nN/A\n\n\nn/a\nn/a\...,...,Informative (Direct or Indirect),NaN,If you have water coming out of your faucet it...,RT @NYCMayorsOffice: If you have water coming ...,Caution and advice,Other,nathancreitz,water coming out of your faucet,NaN,NaN
7,227175874,False,golden,1,11/25/2012 17:24:06,NaN,Other,1.0000,Find open pharmacies,NaN,...,Informative (Direct or Indirect),@RxResponse @WPIX #PSRT #MedsInDisaster,Find open pharmacies after #Frankenstorm #Sand...,Find open pharmacies after #Frankenstorm #Sand...,Caution and advice,Other,RxResponse,open pharmacies\nFind open pharmacies\npharmac...,after #Frankenstorm #Sandy,in the NYC area\nNYC\nin the NYC area\nthe NYC...
8,227175875,True,golden,29,12/10/2012 06:08:53,NYGovCuomo\n.@NYGovCuomo\n@NYGovCuomo\nn/a\n@N...,Other,0.9300,closing of NYC bridges\nclosing of NYC bridges...,close by 7pm\n7pm\n7pm\nn/a\n7pm\nby 7pm\n7pm\...,...,Informative (Direct or Indirect),@NYGovCuomo \nNYGovCuomo,.@NYGovCuomo orders closing of NYC bridges. On...,RT @weatherchannel: .@NYGovCuomo orders closin...,Caution and advice,Other,saraha64,closing of NYC bridges\nclosing of NYC bridges...,by 7pm\n7pm\nclose by 7pm\n7pm.,#NYC\nNYC\nNYC bridges\nN/A
9,227175880,True,golden,93,12/10/2012 14:47:51,\nn/a\n\nna\nn/a\nn/a\nN/A\nN/A\n\n\nN/A\nN/A\...,A hurricane sighting has been reported,0.9180,sandy\nsandy has hit\nsandy\nsandy\nsandy\nsan...,\nn/a\n\nna\nn/a\nn/a\nN/A\nN/A\n\n\nN/A\nN/A\...,...,Informative (Direct or Indirect),"N/A\n""N/A""\nn/a",looks like sandy has hit stourport!,looks like sandy has hit stourport!,Caution and advice,A hurricane sighting has been reported,kathsandford,sandy has hit \nsandy\nsandy has hit stourpor...,"N/A\n""N/A""\nn/a",stourport\nstourport
10,227175881,True,golden,29,12/10/2012 06:05:12,Bloomberg\nBloomberg\n\nn/a\nBloomberg\n\nBloo...,Other,0.9684,Public transportation closed until further not...,until further notice\nuntil further notice\n\n...,...,Informative (Direct),Bloomberg,"Bloomberg: ""Public transportation closed until...","RT @xeni: Bloomberg: ""Public transportation cl...",Caution and advice,A hurricane sighting has been reported\nOther,celestemc,Public transportation closed / NYC subway tunn...,until further notice.\nuntil further notice,NYC / at airport\nNYC
11,227175882,True,golden,29,12/10/2012 06:08:53,n/a\nn/a\nn/a\nn/a\n#Sandy\n\nN/A\n\n\nN/A\n\n...,Other,0.9688,lights go out\nIf your lights go out\nlights g...,n/a\nn/a\nn/a\nn/a\ncouple hours to a couple o...,...,Informative (Direct),NaN,If your lights go out in Toronto it will take ...,"RT @clickflickca: ""If your lights go out in To...",Caution and advice,Other,commoncentsmom,If your lights go out,NaN,Toronto
12,227175883,True,golden,30,12/10/2012 06:08:53,\n\nn/a\nn/a\n#Sandy\n#Sandy\n\n\nFEMA\n\n\nN/...,A shelter is open or available,0.9250,search for open shelters\nsearch for open shel...,\n\nn/a\nn/a\nN/A\nN/A\n\n\n\n\n\nN/A\n\n\n\n\...,...,Informative (Direct),"N/A\n""N/A""",#Sandy East coast search for open shelters by ...,RT @fema: #Sandy East coast search for open sh...,Caution and advice,A shelter is open or available,cubedreamer,search for open shelters \nsearch for open she...,"N/A\n""N/A""\nn/a",East coast\nEast coast\nSandy East coast\n#San...
13,227175887,False,finalized,3,12/8/2012 20:37:58,http://t.co/KQp2f2vX\nN/A\nhttp://t.co/KQp2f2vX,A hurricane warning has been issued or has bee...,0.6619,Remain in your homes\nRemain in your homes whi...,while the storm is in progress\nwhile the stor...,...,Informative (Direct),NaN,Remain in your homes while the storm is in pro...,RT @MikeBloomberg: Remain in your homes while ...,Caution and advice,NaN,JahEmpress,NaN,NaN,NaN
14,227175888,False,finalized,3,12/8/2012 19:34:10,N/A\n\nn/a,Other,1.0000,BE SAFE!!!\nBE SAFE\nBE SAFE,N/A\nn/a\nn/a,...,Informative (Direct),NaN,Everyone in NYC and surrounding areas BE SAFE!...,RT @TeamApoloKarina: Everyone in NYC and surro...,Caution and advice,NaN,jimmbboe,NaN,NaN,NaN
15,227175889,False,finalized,3,12/8/2012 20:47:20,N/A\n@NewYorkPost\n@NewYorkPost,Other,0.6506,empty streets in the concrete jungle\nNew York...,N/A\nN/A\nn/a,...,Informative (Direct),NaN,@NewYorkPost: New York City never sleeps.... #...,"RT @ArturinAbreu: ""@NewYorkPost: New York City...",Caution and advice,NaN,luisdessommes,NaN,NaN,NaN
16,227175890,False,finalized,3,12/8/2012 20:53:21,N/A\nN/A\nn/a,Other,1.0000,phone network overload\nw/phone network overlo...,N/A\nN/A\nn/a,...,Informative (Direct),NaN,NYCÃƒÆ’Ã‚Â¤ÃƒÆ’Ã‚Â³Ãƒâ€šÃ‚Â»ers w/phone networ...,RT @KattHumor: NYCÃƒÆ’Ã‚Â¤ÃƒÆ’Ã‚Â³Ãƒâ€šÃ‚Â»ers...,Caution and advice,NaN,markustedeschii,NaN,NaN,NaN
17,227175891,False,finalized,3,12/8/2012 20:18:01,#Sandy\nN/A\na storm chaser,A hurricane sighting has been reported,0.7003,interviewed a storm chaser\nnext 72 hours in N...,next 72 hours\nnext 72 hours\nnext 72 hours,...,Informative (Direct),NaN,Just interviewed a storm chaser who says this ...,Just interviewed a storm chaser who says this ...,Caution and advice,NaN,MattJohnstonTV,NaN,NaN,NaN
18,227175892,False,finalized,3,12/8/2012 20:57:21,#Sandy\nN/A\nn/a,Other,1.0000,Driving in this is no joke\nDriving in this is...,N/A\nN/A\nn/a,...,Informative (Direct),NaN,Driving in this is no joke this _ÃƒÆ’Ã‚Â´Ãƒâ€š...,Driving in this is no joke this _ÃƒÆ’Ã‚Â´Ãƒâ€š...,Caution and advice,NaN,mocha_93,NaN,NaN,NaN
19,227175893,False,finalized,3,12/10/2012 14:47:51,http://t.co/v8SGOHpT\nhttp://t.co/v8SGOHpT\nht...,A hurricane sighting has been reported,0.7244,crazy waves & wind\ncrazy waves & wind\ncrazy ...,\nn/a\nn/A,...,Informative (Direct),NaN,We've seen some crazy waves & wind here in New...,We've seen some crazy waves & wind here in New...,Caution and advice,NaN,NewBuffaloInn,NaN,NaN,NaN

In [7]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/a154774 2.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head(20))

Rows, Columns: (1987, 16)
Columns: ['_unit_id', '_golden', '_unit_state', '_trusted_judgments', '_last_judgment_at', 'the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event', 'the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event:confidence', 'type_of_message', 'type_of_message:confidence', 'nil', 'the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event_gold', 'tweet', 'tweet_no', 'tweet_no_rt', 'type_of_message_gold', 'user']

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event:confidence,type_of_message,type_of_message:confidence,nil,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event_gold,tweet,tweet_no,tweet_no_rt,type_of_message_gold,user
0,238841781,False,finalized,4,1/2/2013 13:37:11,NaN,NaN,"Informative: offers/gives donations of money, ...",0.2689,NaN,NaN,important --&gt; @JebBush suggests federal gov...,11899,important --&gt; @JebBush suggests federal gov...,NaN,danholler
1,238841782,False,finalized,4,12/24/2012 14:05:56,True,1.0,Not informative: personal only,0.7772,NaN,NaN,@ChrisMara816: Screw #sandy we skipped right a...,116293,@ChrisMara816: Screw #sandy we skipped right a...,NaN,kaatteexo
2,238841783,False,finalized,4,12/24/2012 14:05:56,True,1.0,Informative: information source with extensive...,0.2554,NaN,NaN,On The Learning Network Sandy as a Teaching To...,1091,On The Learning Network Sandy as a Teaching To...,NaN,LotsToLearn
3,238841784,True,golden,35,1/2/2013 13:30:06,True,1.0,"Informative: damage (building, road, lines, etc.)",0.6938,NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
4,238841785,True,golden,28,1/2/2013 13:33:57,True,1.0,"Can not judge (not in English, too short, etc.)",0.5661,NaN,NaN,These Hurricane Sandy pages though,113571,These Hurricane Sandy pages though,"Can not judge (not in English, too short, etc.)",CameronXCV
5,238841786,True,golden,29,1/2/2013 13:35:30,NaN,NaN,Informative: celebrities or authorities react ...,0.3762,NaN,NaN,RT @drewpybell: Romney cancelled his campaign ...,114822,Romney cancelled his campaign stop in ketterin...,Informative: celebrities or authorities react ...,AlyssaDarkow
6,238841787,True,golden,15,1/2/2013 13:08:50,True,1.0,"Can not judge (not in English, too short, etc.)",0.9311,NaN,NaN,RT @TuiterHits: IMPRESIONANTE: Pensaba q era a...,123841,IMPRESIONANTE: Pensaba q era alguna pelÃ­_cula...,"Can not judge (not in English, too short, etc.)",InaKills
7,238841788,True,golden,1,12/24/2012 12:22:40,NaN,NaN,Informative: other,1.0000,NaN,NaN,RT @Be_Determined_: Absolutely incredible. Tom...,118595,Absolutely incredible. Tomb of the Unknown Sol...,Informative: other type of photos/videos (not ...,trashmoney28
8,238841789,True,golden,35,1/2/2013 13:21:55,True,1.0,Informative: caution or advice,0.8847,NaN,NaN,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,GahrSEEuh
9,238841790,False,finalized,5,12/24/2012 14:12:21,True,1.0,Not informative: personal only,0.4284,NaN,NaN,Espectacular timelapse del huracÃ­Ã§n #Sandy: ...,121025,Espectacular timelapse del huracÃ­Ã§n #Sandy: ...,NaN,EnPrimicia
10,238841791,True,golden,34,1/2/2013 13:26:42,NaN,NaN,Informative: casualties (people injured or dead),0.7320,NaN,NaN,US counts cost as Sandy recedes: At least 32 p...,51042,US counts cost as Sandy recedes: At least 32 p...,Informative: casualties (people injured or dea...,deluxekidd
11,238841792,False,finalized,4,12/24/2012 13:53:52,True,1.0,Not informative: personal only,0.7327,NaN,NaN,NYers are tough as nails! RT @isardasorensen R...,55524,NYers are tough as nails! RT @isardasorensen R...,NaN,hellomodko
12,238841793,True,golden,31,1/2/2013 13:18:47,True,1.0,Not informative: personal only,0.8059,NaN,NaN,How are the rest of my #Sandy survivors???? Gi...,49229,How are the rest of my #Sandy survivors???? Gi...,Not informative: personal only,hedwig2212
13,238841794,False,finalized,4,12/24/2012 14:05:56,True,1.0,Informative: caution or advice,0.5031,NaN,NaN,Is in NYC which is on transport and services l...,94732,Is in NYC which is on transport and services l...,NaN,MytonAlps
14,238841795,False,finalized,3,12/24/2012 13:54:14,True,1.0,Not informative: personal only,0.6829,NaN,NaN,RT @1010WINSNewYork: Hurricane Sandy DoesnÃ¤Ã³...,103082,Hurricane Sandy DoesnÃ¤Ã³Â»t Halt NYCÃ¤Ã³Â»s D...,NaN,IMColey
15,238841796,False,finalized,3,12/24/2012 13:49:18,True,1.0,Not informative: personal only,0.6581,NaN,NaN,The wind is picking up... #Sandy,106916,The wind is picking up... #Sandy,NaN,alicejane011
16,238841798,False,finalized,4,12/24/2012 14:07:12,True,1.0,"Can not judge (not in English, too short, etc.)",0.7853,NaN,NaN,FuracÃ­Â£o Sandy promete tocar o putedo em Nov...,140537,FuracÃ­Â£o Sandy promete tocar o putedo em Nov...,NaN,marciodolzan
17,238841799,False,finalized,4,12/24/2012 13:53:52,NaN,NaN,Not informative: unrelated to the disaster,0.7731,NaN,NaN,#mentionto Figure out this is the ruse!!! http...,70787,#mentionto Figure out this is the ruse!!! http...,NaN,JessieBradshaw8
18,238841800,True,golden,26,1/2/2013 13:35:30,NaN,NaN,"Informative: offers/gives donations of money, ...",0.4477,NaN,NaN,RT @its_tasha_baby: RT @HuffingtonPost: MTA to...,37786,MTA to provide free buses in NYC starting at 5...,"Informative: offers/gives donations of money, ...",SweetTeaNPearls
19,238841801,True,golden,28,1/2/2013 13:35:30,True,1.0,"Can not judge (not in English, too short, etc.)",0.9239,NaN,NaN,Mak!? Skalian aja badai sandy di NYC jg gara2 ...,16022,Mak!? Skalian aja badai sandy di NYC jg gara2 ...,"Can not judge (not in English, too short, etc.)",pitutatitut

In [8]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/f157060.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
display(df.head(20))

Rows, Columns: (2847, 22)

,_unit_id,_created_at,_golden,_id,_missed,_started_at,_tainted,_channel,_trust,_worker_id,...,_city,_ip,word_or_shortphrase,instruction,tweet,tweet_no,tweet_no_rt,type_of_message,type_of_messageconfidence,word_or_shortphrase_gold
0,240632763,1/2/2013 15:03:51,True,797143942,False,1/2/2013 15:01:51,False,instagc,0.9167,13441146,...,Cleveland,98.18.123.70,homes in the U.S. are now without power post-s...,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
1,240632763,1/2/2013 15:06:13,True,797145153,False,1/2/2013 15:03:16,False,instagc,0.8750,14893322,...,Lynchburg,96.235.212.161,8 million homes in the U.S. are now without power,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
2,240632763,1/2/2013 15:09:30,True,797146945,False,1/2/2013 15:06:41,False,instagc,1.0000,12960437,...,Point Pleasant,173.81.178.140,8 million homes in the U.S. are now without power,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
3,240632763,1/2/2013 15:20:43,True,797152214,NaN,1/2/2013 15:17:00,False,instagc,0.7500,14475081,...,Dunlap,98.143.6.78,8 million homes in the U.S. are now without power,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
4,240632763,1/2/2013 15:32:29,True,797157904,NaN,1/2/2013 15:30:17,False,instagc,1.0000,14049868,...,Toledo,131.183.0.122,without power,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
5,240632763,1/2/2013 15:42:27,True,797163197,False,1/2/2013 15:40:36,False,golddiggergpt,0.9286,15038871,...,Port Richey,68.200.93.250,homes,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
6,240632763,1/3/2013 10:42:22,True,798237936,True,1/3/2013 10:38:52,False,extralunchmoney,0.8636,15113061,...,Saint Johns,50.36.97.129,8 million homes,"names a structure, road, service, line, etc. t...",RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",0.6938,power\nwithout power\n8 million homes in the U...
7,240632764,1/2/2013 15:11:18,True,797147824,False,1/2/2013 15:06:03,False,instagc,0.7500,14475081,...,Dunlap,98.143.6.78,The time for evacuation is over. Conditions ar...,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
8,240632764,1/2/2013 15:13:14,True,797148629,NaN,1/2/2013 15:07:55,False,instagc,1.0000,14049868,...,Toledo,131.183.0.122,Please stay where you are,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
9,240632764,1/2/2013 15:14:39,True,797149299,False,1/2/2013 15:06:57,False,instagc,0.8750,14893322,...,Lynchburg,96.235.212.161,Conditions are dangerous and will get worse. P...,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
10,240632764,1/2/2013 15:16:12,True,797149991,True,1/2/2013 15:14:31,False,instagc,1.0000,12960437,...,Point Pleasant,173.81.178.140,hurricane #sandy,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
11,240632764,1/2/2013 15:22:59,True,797152987,NaN,1/2/2013 15:19:35,False,instagc,0.7500,14452255,...,Elmore,68.207.200.230,Please stay where you are,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
12,240632764,1/2/2013 15:40:58,True,797162101,False,1/2/2013 15:38:27,False,instagc,0.8000,13651583,...,Virginia,173.21.170.197,evacuation,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
13,240632764,1/2/2013 15:41:26,True,797162317,NaN,1/2/2013 15:37:56,False,instagc,1.0000,14296101,...,Buffalo,216.105.230.23,Conditions are dangerous and will get worse,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
14,240632764,1/2/2013 15:47:22,True,797165767,NaN,1/2/2013 15:43:43,False,instagc,1.0000,15124146,...,Norwalk,24.189.161.45,Please stay where you are,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
15,240632764,1/2/2013 16:00:33,True,797172497,True,1/2/2013 15:58:01,False,golddiggergpt,0.9286,15038871,...,Port Richey,68.200.93.250,onditions are dangerous and will get worse,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
16,240632764,1/2/2013 16:19:50,True,797183557,False,1/2/2013 16:12:48,False,instagc,0.8750,13864884,...,Buhler,64.6.130.175,Conditions are dangerous and will get worse. P...,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
17,240632764,1/2/2013 16:20:55,True,797184238,True,1/2/2013 16:13:48,False,cbf,0.7500,7762692,...,Seneca,69.59.88.93,City,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
18,240632764,1/2/2013 16:21:18,True,797184402,False,1/2/2013 16:19:03,False,instagc,1.0000,14853026,...,Mifflinville,72.79.132.143,Conditions are dangerous and will get worse. P...,warns about a potential hazard or advices what...,RT @MikeBloomberg: The time for evacuation is ...,90936,The time for evacuation is over. Conditions ar...,Informative: caution or advice,0.8847,Please stay where you are\nPlease stay where y...
19,240632765,1/2/2013 15:01:01,True,797142380,NaN,1/2/2013 14:57:46,False,instagc,0.7500,14452255,...,Elmore,68.207.200.230,32,indicates who has (or how many people have) be...,US counts cost as Sandy recedes: At least 32 p...,51042,US counts cost as Sandy recedes: At least 32 p...,Informative: casualties (people injured or dead),0.7320,32 people\n32 people have been killed\n32\nAt ...

In [9]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/data/f154774.csv")
df = pd.read_csv(path)

print("Rows, Columns:", df.shape)
display(df.head(20))

Rows, Columns: (7115, 23)

,_unit_id,_created_at,_golden,_id,_missed,_started_at,_tainted,_channel,_trust,_worker_id,...,_ip,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event,type_of_message,nil,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event_gold,tweet,tweet_no,tweet_no_rt,type_of_message_gold,user
0,238841781,12/24/2012 13:41:45,False,787060207,NaN,12/24/2012 13:37:36,False,instagc,0.7333,14425455,...,69.136.129.135,NaN,Informative: other,NaN,NaN,important --&gt; @JebBush suggests federal gov...,11899,important --&gt; @JebBush suggests federal gov...,NaN,danholler
1,238841781,12/24/2012 13:44:17,False,787063467,NaN,12/24/2012 13:39:45,False,instagc,0.8333,13441146,...,98.18.108.46,NaN,"Informative: offers/gives donations of money, ...",NaN,NaN,important --&gt; @JebBush suggests federal gov...,11899,important --&gt; @JebBush suggests federal gov...,NaN,danholler
2,238841781,12/24/2012 13:54:14,False,787076220,NaN,12/24/2012 13:51:24,False,golddiggergpt,0.8182,11092052,...,108.92.226.94,NaN,Informative: celebrities or authorities react ...,NaN,NaN,important --&gt; @JebBush suggests federal gov...,11899,important --&gt; @JebBush suggests federal gov...,NaN,danholler
3,238841781,1/2/2013 13:37:11,False,797105603,NaN,1/2/2013 13:34:10,False,instagc,0.7143,13166748,...,71.200.11.183,NaN,Informative: caution or advice,NaN,NaN,important --&gt; @JebBush suggests federal gov...,11899,important --&gt; @JebBush suggests federal gov...,NaN,danholler
4,238841782,12/24/2012 13:24:41,False,787038536,NaN,12/24/2012 13:22:21,False,instagc,0.9048,14031300,...,70.247.113.51,True,Not informative: personal only,NaN,NaN,@ChrisMara816: Screw #sandy we skipped right a...,116293,@ChrisMara816: Screw #sandy we skipped right a...,NaN,kaatteexo
5,238841782,12/24/2012 13:45:21,False,787064937,NaN,12/24/2012 13:42:10,False,instagc,0.7917,12973811,...,108.94.86.115,NaN,"Can not judge (not in English, too short, etc.)",NaN,NaN,@ChrisMara816: Screw #sandy we skipped right a...,116293,@ChrisMara816: Screw #sandy we skipped right a...,NaN,kaatteexo
6,238841782,12/24/2012 13:47:04,False,787067034,NaN,12/24/2012 13:45:27,False,instagc,1.0000,13024538,...,76.5.55.227,NaN,Not informative: personal only,NaN,NaN,@ChrisMara816: Screw #sandy we skipped right a...,116293,@ChrisMara816: Screw #sandy we skipped right a...,NaN,kaatteexo
7,238841782,12/24/2012 14:05:56,False,787091330,NaN,12/24/2012 14:03:55,False,instagc,0.8571,14343804,...,98.235.250.131,NaN,Not informative: personal only,NaN,NaN,@ChrisMara816: Screw #sandy we skipped right a...,116293,@ChrisMara816: Screw #sandy we skipped right a...,NaN,kaatteexo
8,238841783,12/24/2012 13:19:48,False,787032671,NaN,12/24/2012 13:16:35,False,instagc,0.9048,14031300,...,70.247.113.51,True,Informative: other type of photos/videos (not ...,NaN,NaN,On The Learning Network Sandy as a Teaching To...,1091,On The Learning Network Sandy as a Teaching To...,NaN,LotsToLearn
9,238841783,12/24/2012 13:35:58,False,787052486,NaN,12/24/2012 13:32:04,False,golddiggergpt,0.8889,10491104,...,24.196.110.185,NaN,Informative: other,NaN,NaN,On The Learning Network Sandy as a Teaching To...,1091,On The Learning Network Sandy as a Teaching To...,NaN,LotsToLearn
10,238841783,12/24/2012 13:44:53,False,787064400,NaN,12/24/2012 13:42:08,False,instagc,0.9091,14545842,...,74.73.57.78,NaN,Informative: information source with extensive...,NaN,NaN,On The Learning Network Sandy as a Teaching To...,1091,On The Learning Network Sandy as a Teaching To...,NaN,LotsToLearn
11,238841783,12/24/2012 14:05:56,False,787091332,NaN,12/24/2012 14:03:55,False,instagc,0.8571,14343804,...,98.235.250.131,NaN,Not informative: personal only,NaN,NaN,On The Learning Network Sandy as a Teaching To...,1091,On The Learning Network Sandy as a Teaching To...,NaN,LotsToLearn
12,238841784,12/24/2012 13:06:35,True,787018071,NaN,12/24/2012 12:56:07,False,fusioncash,0.8750,14888550,...,24.75.117.149,NaN,"Informative: damage (building, road, lines, et...",NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
13,238841784,12/24/2012 13:21:40,True,787035001,False,12/24/2012 13:20:40,False,fusioncash,0.7000,13063182,...,98.124.116.69,NaN,Informative: celebrities or authorities react ...,NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
14,238841784,12/24/2012 13:26:37,True,787040657,NaN,12/24/2012 13:24:42,False,instagc,0.9048,14031300,...,70.247.113.51,True,"Informative: damage (building, road, lines, etc.)",NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
15,238841784,12/24/2012 13:27:20,True,787041520,False,12/24/2012 13:23:26,False,instagc,0.8571,14343804,...,98.235.250.131,NaN,Informative: information source with extensive...,NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
16,238841784,12/24/2012 13:35:58,True,787052488,NaN,12/24/2012 13:32:04,False,golddiggergpt,0.8889,10491104,...,24.196.110.185,NaN,"Informative: damage (building, road, lines, etc.)",NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
17,238841784,12/24/2012 13:36:48,True,787053524,NaN,12/24/2012 13:34:28,False,golddiggergpt,0.8182,11092052,...,108.92.226.94,NaN,"Informative: damage (building, road, lines, etc.)",NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
18,238841784,12/24/2012 13:37:43,True,787054622,False,12/24/2012 13:36:38,False,instagc,0.8333,13441146,...,98.18.108.46,NaN,Informative: information source with extensive...,NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06
19,238841784,12/24/2012 13:42:05,True,787060644,NaN,12/24/2012 13:38:45,False,instagc,0.8889,13608190,...,98.25.35.43,NaN,"Informative: damage (building, road, lines, etc.)",NaN,NaN,RT @nytimes: More than 8 million homes in the ...,53537,More than 8 million homes in the U.S. are now ...,"Informative: damage (building, road, lines, etc.)",brunamacedo06

In [10]:
import os
import glob
import pandas as pd
from tqdm import tqdm
from IPython.display import display

data_folder = "/Users/munakandel/Desktop/community resiliance/data"
csv_files = glob.glob(os.path.join(data_folder, "*.csv"))
print("CSV files found:", len(csv_files))

CSV files found: 8

In [11]:
df_list = []
for file in tqdm(csv_files):
    df = pd.read_csv(file)
    df["source_file"] = os.path.basename(file)
    df_list.append(df)

merged_df = pd.concat(df_list, ignore_index=True)
print("Merging complete. Shape:", merged_df.shape)

100%|██████████| 8/8 [00:00<00:00, 137.91it/s]

Merging complete. Shape: (13858, 59)

In [12]:
display(merged_df.head(20))

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,text_no_rt,tweet,...,source,type_of_advice_or_caution,type_of_advice_or_caution:confidence,when,where,source_gold,type_of_advice_or_caution_gold,when_gold,where_gold,the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event:confidence
0,223607030,False,finalized,3.0,11/14/2012 03:26:51,Casualties and damage,1.0000,NaN,28 deaths due to Hurricane Sandy | Charlotte t...,RT @HenderGrande: 28 deaths due to Hurricane S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,223607031,True,golden,3.0,11/14/2012 03:41:27,Casualties and damage,1.0000,Casualties and damage,Sandy kills 50 people nationwide 18 were New Y...,Sandy kills 50 people nationwide 18 were New Y...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,223607032,False,finalized,3.0,11/14/2012 03:38:40,Casualties and damage,0.6849,NaN,RT @nowthised: Wider shot of scaffolding toppl...,RT @twc_hurricane: RT @nowthised: Wider shot o...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,223607033,True,golden,10.0,11/14/2012 03:35:39,Caution and advice,0.8900,Caution and advice,#Sandy will be onshore about 6pm. Slightly fas...,RT @growingwisdom: #Sandy will be onshore abou...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,223607034,True,golden,7.0,11/14/2012 03:36:35,"Donations of money, goods or services",0.5727,"Donations of money, goods or services",@ChrisFRC lost startups can go to @AlleyNYC. T...,@ChrisFRC lost startups can go to @AlleyNYC. T...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,223607035,True,golden,9.0,11/14/2012 03:26:01,Casualties and damage,1.0000,Casualties and damage,Sandy death toll climbs; millions remain witho...,Sandy death toll climbs; millions remain witho...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,223607036,True,golden,3.0,11/14/2012 03:42:00,Casualties and damage,1.0000,Casualties and damage,Extensive flooding in all subway tunnels says ...,RT @emmagkeller: Extensive flooding in all sub...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,223607037,True,golden,10.0,11/14/2012 03:35:39,"Donations of money, goods or services",1.0000,"Donations of money, goods or services",400 Volunteers are needed for areas that took ...,400 Volunteers are needed for areas that took ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,223607038,True,golden,9.0,11/14/2012 03:31:53,Caution and advice,0.8735,Caution and advice,Storm just now hitting Jersey...Milford is fee...,Storm just now hitting Jersey...Milford is fee...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,223607039,True,golden,10.0,11/14/2012 03:25:45,Caution and advice,0.6982,Caution and advice,City Public Schools will be closed Wednesday 1...,RT @ChrisCQuinn: City Public Schools will be c...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,223607040,True,golden,5.0,11/14/2012 03:38:01,Information Source,0.4343,Caution and advice,checked the news. yes there is schol tomoro. s...,checked the news. yes there is schol tomoro. s...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,223607041,True,golden,10.0,11/14/2012 03:33:59,Caution and advice,0.5830,Caution and advice,Hurricane Sandy is going to fill the subways w...,RT @JessieWessie33: Hurricane Sandy is going t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,223607042,True,golden,6.0,11/14/2012 03:38:40,Caution and advice,0.4721,Caution and advice,Omg NYC is now impacted by hurricane #Sandy,Omg NYC is now impacted by hurricane #Sandy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,223607043,True,golden,11.0,11/14/2012 03:33:59,Casualties and damage,0.8990,Casualties and damage,40 people killed during Super Storm Sandy! Don...,40 people killed during Super Storm Sandy! Don...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,223607044,True,golden,11.0,11/14/2012 03:33:59,Unknown,0.7170,Unknown,Due to Hurricane #Sandy the @90210 episode is ...,RT @ryanlochte: Due to Hurricane #Sandy the @9...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,223607045,True,golden,11.0,11/14/2012 03:34:01,Unknown,0.6308,Unknown,they just showed a dude on a Jet Ski off of Ba...,they just showed a dude on a Jet Ski off of Ba...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,223607046,True,golden,11.0,11/14/2012 03:30:21,Casualties and damage,0.7985,Casualties and damage,+++BREAKING+++ New Jersey sewage plant hit by ...,+++BREAKING+++ New Jersey sewage plant hit by ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,223607047,True,golden,12.0,11/14/2012 03:18:55,Caution and advice,0.8484,Caution and advice,NYC ALERT: All pets are accepted on the subway...,RT @ASPCA: NYC ALERT: All pets are accepted on...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,223607048,True,golden,12.0,11/14/2012 03:31:53,Casualties and damage,0.5785,Casualties and damage,A boat lies across the railroad tracks near Me...,RT @aadragna: A boat lies across the railroad ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,223607049,True,golden,10.0,11/14/2012 03:30:52,Casualties and damage,0.8883,Casualties and damage,We are worried about the #UN documents histori...,RT @UNLibrary: We are worried about the #UN do...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
save_path = "/Users/munakandel/Desktop/community resiliance/community_resilience_merged.csv"
os.makedirs(os.path.dirname(save_path), exist_ok=True)
merged_df.to_csv(save_path, index=False)
print("Merged dataset saved at:", save_path)

Merged dataset saved at: /Users/munakandel/Desktop/community resiliance/community_resilience_merged.csv

In [14]:
import os
print(os.path.expanduser("~/Desktop/community resiliance/data/community_resilience_merged.csv"))

/Users/munakandel/Desktop/community resiliance/data/community_resilience_merged.csv

In [15]:
import os
import glob
import pandas as pd

data_folder = os.path.expanduser("~/Desktop/community resiliance/data")
csv_files = glob.glob(os.path.join(data_folder, "*.csv"))

col_freq = {}

for f in csv_files:
    df = pd.read_csv(f, nrows=1)  # only read header
    for col in df.columns:
        col_freq[col] = col_freq.get(col, 0) + 1

# Convert to sorted DataFrame
col_freq_df = pd.DataFrame(
    list(col_freq.items()), columns=["column", "file_count"]
).sort_values(by="file_count", ascending=False)

print(col_freq_df)

# Optionally save to CSV
save_path = os.path.expanduser("~/Desktop/community resiliance/column_frequency_across_files.csv")
col_freq_df.to_csv(save_path, index=False)
print("Saved column frequency report at:", save_path)

                                               column  file_count
0                                            _unit_id           8
1                                             _golden           8
9                                               tweet           8
11                                               user           7
2                                         _unit_state           6
3                                  _trusted_judgments           6
4                                   _last_judgment_at           6
8                                          text_no_rt           5
25                                    type_of_message           4
10                                               type           4
34                                           category           3
30                               type_of_message_gold           3
28                                           tweet_no           3
26                                                nil           3
29                                        tweet_no_rt           3
15                                        _started_at           2
13                                                _id           2
16                                           _tainted           2
5                                          choose_one           2
33                                               what           2
31                         type_of_message:confidence           2
6                               choose_one:confidence           2
7                                     choose_one_gold           2
12                                        _created_at           2
27  the_author_of_the_tweet_seems_to_be_an_eye_wit...           2
36                                          what_gold           2
14                                            _missed           2
20                                           _country           2
24  the_author_of_the_tweet_seems_to_be_an_eye_wit...           2
18                                             _trust           2
19                                         _worker_id           2
17                                           _channel           2
21                                            _region           2
22                                              _city           2
23                                                _ip           2
56                                         where_gold           1
55                                          when_gold           1
46                          type_of_messageconfidence           1
54                     type_of_advice_or_caution_gold           1
53                                        source_gold           1
52                                              where           1
51                                               when           1
50               type_of_advice_or_caution:confidence           1
49                          type_of_advice_or_caution           1
48                                             source           1
47                           word_or_shortphrase_gold           1
42                      people_or_infrastructure_gold           1
45                                        instruction           1
44                                word_or_shortphrase           1
43  what_infrastructure_was_damaged_if_infrastruct...           1
41            hom_many_injured_or_dead_if_people_gold           1
40  what_infrastructure_was_damaged_if_infrastructure           1
39                people_or_infrastructure:confidence           1
38                           people_or_infrastructure           1
37                 hom_many_injured_or_dead_if_people           1
35             url_or_name_of_the_stationchannel_gold           1
32                  url_or_name_of_the_stationchannel           1
57  the_author_of_the_tweet_seems_to_be_an_eye_wit...           1
Saved column frequency report at: /Users/munakandel/Desktop/community resiliance/column_frequency_across_files.csv

In [16]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/community_resilience_merged.csv")
df = pd.read_csv(path)

null_percentage = (df.isnull().mean() * 100).round(2)

print("Null % in each column:\n")
print(null_percentage)

Null % in each column:

_unit_id                                                                       0.00
_golden                                                                        0.00
_unit_state                                                                   71.89
_trusted_judgments                                                            71.89
_last_judgment_at                                                             71.89
choose_one                                                                    88.87
choose_one:confidence                                                         88.87
choose_one_gold                                                               99.34
text_no_rt                                                                    86.22
tweet                                                                          0.00
type                                                                          93.44
user                                                                          20.54
source_file                                                                    0.00
_created_at                                                                   28.11
_id                                                                           28.11
_missed                                                                       97.54
_started_at                                                                   28.11
_tainted                                                                      28.11
_channel                                                                      28.11
_trust                                                                        28.11
_worker_id                                                                    28.11
_country                                                                      28.11
_region                                                                       29.34
_city                                                                         29.34
_ip                                                                           28.11
the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event               93.79
type_of_message                                                               13.27
nil                                                                           99.96
the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event_gold          99.64
tweet_no                                                                      13.78
tweet_no_rt                                                                   13.78
type_of_message_gold                                                          91.26
type_of_message:confidence                                                    85.16
url_or_name_of_the_stationchannel                                             99.49
what                                                                          98.59
category                                                                      97.36
url_or_name_of_the_stationchannel_gold                                        99.83
what_gold                                                                     99.74
hom_many_injured_or_dead_if_people                                            98.77
people_or_infrastructure                                                      98.77
people_or_infrastructure:confidence                                           98.77
what_infrastructure_was_damaged_if_infrastructure                             98.77
hom_many_injured_or_dead_if_people_gold                                       99.91
people_or_infrastructure_gold                                                 99.77
what_infrastructure_was_damaged_if_infrastructure_gold                        99.85
word_or_shortphrase                                                           79.67
instruction                                                                   79.46
type_of_messageconfidence                                                     79.46
word_or_shortphrase_gold                                                      97.54
source                                                                        99.12
type_of_advice_or_caution                                                     99.09
type_of_advice_or_caution:confidence                                          99.09
when                                                                          99.11
where                                                                         99.09
source_gold                                                                   99.96
type_of_advice_or_caution_gold                                                99.91
when_gold                                                                     99.94
where_gold                                                                    99.92
the_author_of_the_tweet_seems_to_be_an_eye_witness_of_the_event:confidence    97.29
dtype: float64

In [17]:
import os
import pandas as pd

# Load merged unified dataset
path = os.path.expanduser("~/Desktop/community resiliance/community_resilience_merged.csv")
df = pd.read_csv(path)

# Keep only the columns you specified
keep_cols = [
    "_unit_id", "_golden", "tweet", "user", "source_file",
    "_created_at", "_id", "_started_at", "_country",
    "_region", "_city", "_ip", "type_of_message", "tweet_no"
]

# Some names you listed might slightly differ in the real file, so pick intersection to avoid KeyError
final_cols = [c for c in keep_cols if c in df.columns]
df = df[final_cols]

# Save new CSV
save_path = os.path.expanduser("~/Desktop/community resiliance/useful.csv")
df.to_csv(save_path, index=False)

print("Rows, Columns:", df.shape)
print("Useful columns kept:", final_cols)
print("File saved at:", save_path)

Rows, Columns: (13858, 14)
Useful columns kept: ['_unit_id', '_golden', 'tweet', 'user', 'source_file', '_created_at', '_id', '_started_at', '_country', '_region', '_city', '_ip', 'type_of_message', 'tweet_no']
File saved at: /Users/munakandel/Desktop/community resiliance/useful.csv

In [18]:
import os
import pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/useful.csv")
df = pd.read_csv(path)

(df.isnull().mean() * 100).round(2)

_unit_id            0.00
_golden             0.00
tweet               0.00
user               20.54
source_file         0.00
_created_at        28.11
_id                28.11
_started_at        28.11
_country           28.11
_region            29.34
_city              29.34
_ip                28.11
type_of_message    13.27
tweet_no           13.78
dtype: float64

In [19]:
import os, re, pandas as pd

path = os.path.expanduser("~/Desktop/community resiliance/useful.csv")
df = pd.read_csv(path)

df["tweet_clean"] = df["tweet"].astype(str)

def clean_text(s):
    s = s.lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)
    s = re.sub(r"@\w+", " ", s)
    s = s.replace("#", " ")
    s = re.sub(r"\s+", " ", s).strip()
    return s

df["tweet_clean"] = df["tweet_clean"].apply(clean_text)

# Save cleaned file
out = os.path.expanduser("~/Desktop/community resiliance/useful_clean.csv")
df.to_csv(out, index=False)

print("Cleaned file saved:", out)
print(df[["tweet","tweet_clean"]].head(10))

Cleaned file saved: /Users/munakandel/Desktop/community resiliance/useful_clean.csv
                                               tweet  \
0  RT @HenderGrande: 28 deaths due to Hurricane S...
1  Sandy kills 50 people nationwide 18 were New Y...
2  RT @twc_hurricane: RT @nowthised: Wider shot o...
3  RT @growingwisdom: #Sandy will be onshore abou...
4  @ChrisFRC lost startups can go to @AlleyNYC. T...
5  Sandy death toll climbs; millions remain witho...
6  RT @emmagkeller: Extensive flooding in all sub...
7  400 Volunteers are needed for areas that took ...
8  Storm just now hitting Jersey...Milford is fee...
9  RT @ChrisCQuinn: City Public Schools will be c...

                                         tweet_clean
0  rt : 28 deaths due to hurricane sandy | charlo...
1  sandy kills 50 people nationwide 18 were new y...
2  rt : rt : wider shot of scaffolding toppling c...
3  rt : sandy will be onshore about 6pm. slightly...
4  lost startups can go to . the alley nyc locate...
5  sandy death toll climbs; millions remain witho...
6  rt : extensive flooding in all subway tunnels ...
7  400 volunteers are needed for areas that took ...
8  storm just now hitting jersey...milford is fee...
9  rt : city public schools will be closed wednes...

In [20]:
import numpy as np
import pandas as pd

# Parse timestamps safely
df["_created_at"] = pd.to_datetime(df["_created_at"], errors="coerce")
df["_started_at"] = pd.to_datetime(df["_started_at"], errors="coerce")

# Use created_at as primary event time
event_time = df["_created_at"]

# Compute hours since event ONLY where time exists
max_time = event_time.max()
df["hours_since_event"] = (max_time - event_time).dt.total_seconds() / 3600

# Initialize recency_score as NaN
df["recency_score"] = np.nan

# Apply exponential decay ONLY to rows with valid timestamps
mask_valid_time = df["hours_since_event"].notna()
df.loc[mask_valid_time, "recency_score"] = np.exp(
    -0.1 * df.loc[mask_valid_time, "hours_since_event"]
)

# Clean up intermediate column
df.drop(columns=["hours_since_event"], inplace=True, errors="ignore")

# Sanity check
df["recency_score"].describe()

count    9.962000e+03
mean     1.661965e-01
std      2.200963e-01
min      3.875113e-11
25%      9.518390e-02
50%      1.007502e-01
75%      1.261367e-01
max      1.000000e+00
Name: recency_score, dtype: float64

In [21]:
import pandas as pd

# Make sure df exists first
df_model = df.copy()

print("df_model created. Shape:", df_model.shape)

df_model created. Shape: (13858, 16)

In [22]:
import numpy as np
import pandas as pd

def simplify_message_type(x):
    if pd.isna(x):
        return np.nan
    x = x.lower()
    if "not informative: personal" in x:
        return "personal"
    elif "informative" in x:
        return "informative"
    else:
        return "other"

# Create simplified label column
df_model["type_simple"] = df_model["type_of_message"].apply(simplify_message_type)

print(df_model["type_simple"].value_counts(dropna=False))

type_simple
informative    7376
personal       3357
NaN            1839
other          1286
Name: count, dtype: int64

In [23]:
train_df = df_model[
    df_model["type_simple"].notna() &
    (df_model["tweet_clean"].str.strip() != "")
].copy()

X_train = train_df["tweet_clean"].tolist()
y_train = train_df["type_simple"].tolist()

print("Training samples:", len(train_df))

Training samples: 12015

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

type_imputer = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=30000,
        ngram_range=(1, 2),
        stop_words="english",
        min_df=5
    )),
    ("clf", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        solver="lbfgs"
    ))
])

type_imputer.fit(X_train, y_train)
print("Model trained to learn message-type patterns")

Model trained to learn message-type patterns

In [25]:
mask_missing = (
    df_model["type_simple"].isna() &
    (df_model["tweet_clean"].str.strip() != "")
)

X_missing = df_model.loc[mask_missing, "tweet_clean"].tolist()

print("Rows to impute:", len(X_missing))

Rows to impute: 1836

In [26]:
probs = type_imputer.predict_proba(X_missing)
preds = type_imputer.classes_[probs.argmax(axis=1)]
conf = probs.max(axis=1)

In [27]:
CONF_THRESHOLD = 0.70  # safe choice

df_model.loc[mask_missing, "type_simple"] = np.where(
    conf >= CONF_THRESHOLD,
    preds,
    "other"
)

print(df_model["type_simple"].value_counts())

type_simple
informative    8000
personal       3570
other          2285
Name: count, dtype: int64

In [28]:
# Create a final message type column
df_model["type_of_message_imputed"] = df_model["type_simple"]

In [29]:
output_path = os.path.expanduser(
    "~/Desktop/community resiliance/useful_with_imputed_types.csv"
)

df_model.to_csv(output_path, index=False)

print("CSV saved at:", output_path)

CSV saved at: /Users/munakandel/Desktop/community resiliance/useful_with_imputed_types.csv

In [30]:
# Import transformer pipeline for LLM-based tweet classification
# and pandas/numpy for handling and storing tweet data and predictions
from transformers import pipeline
import pandas as pd
import numpy as np

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [31]:
# Load a large pre-trained transformer (LLM) for zero-shot tweet classification
# Used to automatically label tweets as emergency, support offer, or neutral without manual annotation
zero_shot_classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

Loading weights: 100%|██████████| 515/515 [00:00<00:00, 1661.29it/s, Materializing param=model.shared.weight]

In [32]:
# Define target categories for automatic tweet classification:
# emergency requests, support offers, and neutral (general information)
candidate_labels = ["emergency", "support offer", "neutral"]

In [33]:
# Automatically classify each tweet into emergency, support offer, or neutral
    # using a pre-trained LLM (BART) and return both the predicted label and confidence score
def zero_shot_label(text):
    if not isinstance(text, str) or text.strip() == "":
        return None, None

    result = zero_shot_classifier(
        text,
        candidate_labels,
        hypothesis_template="This tweet is about {}."
    )

    label = result["labels"][0] # Highest-confidence category
    score = result["scores"][0] # Confidence of the prediction

    return label, score

In [34]:
# Automatically label each tweet as emergency, support offer, or neutral
# using a zero-shot LLM, and store both the predicted label and confidence score
df_model["auto_label"], df_model["auto_label_score"] = zip(*df_model["tweet_clean"].apply(zero_shot_label))

In [35]:
# Check how many tweets were automatically labeled as emergency, support offer, or neutral by the LLM
df_model["auto_label"].value_counts()

auto_label
emergency        8492
support offer    3862
neutral          1497
Name: count, dtype: int64

In [36]:
def finalize_label(row):
    label = row["auto_label"]
    score = row["auto_label_score"]

    if label == "emergency" and score >= 0.40:
        return "emergency"
    elif label == "support offer" and score >= 0.50:
        return "support offer"
    else:
        return "neutral"

df_model["auto_label_final"] = df_model.apply(finalize_label, axis=1)

df_model["auto_label_final"].value_counts()

auto_label_final
emergency        8364
support offer    2966
neutral          2528
Name: count, dtype: int64

In [37]:
auto_labeled_path = os.path.expanduser(
    "~/Desktop/community resiliance/auto_labeled_tweets.csv"
)

df_model.to_csv(auto_labeled_path, index=False)

print("Auto-labeled dataset saved at:", auto_labeled_path)

Auto-labeled dataset saved at: /Users/munakandel/Desktop/community resiliance/auto_labeled_tweets.csv

In [38]:
from transformers import pipeline


zs_roberta = pipeline(
    "zero-shot-classification",
    model="roberta-large-mnli"
)

candidate_labels = ["emergency", "support offer", "neutral"]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 1802.17it/s, Materializing param=roberta.encoder.layer.23.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-large-mnli
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [39]:
def zero_shot_predict(model, text):
    if not isinstance(text, str) or text.strip() == "":
        return None, None

    out = model(
        text,
        candidate_labels,
        hypothesis_template="This tweet is about {}."
    )

    return out["labels"][0], out["scores"][0]

In [40]:
HIGH_CONF = 0.6

df_agree = df_model[
    df_model["auto_label_score"] >= HIGH_CONF
].copy()

print("Tweets used for agreement check:", len(df_agree))

Tweets used for agreement check: 9191

In [41]:
df_agree["roberta_label"], df_agree["roberta_score"] = zip(*df_agree["tweet_clean"].apply(
    lambda x: zero_shot_predict(zs_roberta, x)
))

In [42]:
df_agree["agreement"] = (
    df_agree["auto_label"] == df_agree["roberta_label"]
)

agreement_rate = df_agree["agreement"].mean() * 100
agreement_rate

np.float64(86.68262430638669)

In [43]:
agreement_by_class = (
    df_agree
    .groupby("auto_label")["agreement"]
    .mean()
    .sort_values(ascending=False)
)

agreement_by_class

auto_label
emergency        0.970732
support offer    0.676936
neutral          0.432866
Name: agreement, dtype: float64

In [44]:
import numpy as np
import pandas as pd

# Count how many times each cleaned tweet appears
tweet_freq = (
    df_model["tweet_clean"]
    .value_counts()
    .reset_index()
)

tweet_freq.columns = ["tweet_clean", "retweet_count"]

# Merge back
df_model = df_model.merge(
    tweet_freq,
    on="tweet_clean",
    how="left"
)

# Log-normalized retweet score
df_model["retweet_score"] = np.log1p(df_model["retweet_count"])

In [45]:
final_columns = [
    "_unit_id",
    "_golden",
    "tweet",
    "user",
    "source_file",
    "_created_at",
    "_id",
    "_started_at",
    "_country",
    "_region",
    "_city",
    "_ip",
    "type_of_message",
    "tweet_no",
    "tweet_clean",
    "recency_score",
    "type_simple",
    "type_of_message_imputed",
    "auto_label",
    "auto_label_score",
    "auto_label_final",
    "retweet_count",
    "retweet_score"
]

final_df = df_model[final_columns].copy()

In [46]:
final_save_path = os.path.expanduser(
    "~/Desktop/community resiliance/final_modeling_dataset.csv"
)

final_df.to_csv(final_save_path, index=False)

print("Final dataset saved at:", final_save_path)
print("\nFinal label distribution:")

Final dataset saved at: /Users/munakandel/Desktop/community resiliance/final_modeling_dataset.csv

Final label distribution:

In [47]:
import pandas as pd
import os

path = os.path.expanduser(
    "~/Desktop/community resiliance/final_modeling_dataset.csv"
)

df = pd.read_csv(path)

# Remove duplicate tweets for training
df_unique = df.drop_duplicates(subset="tweet_clean").copy()

print("Unique rows:", len(df_unique))

Unique rows: 2873

In [48]:
label_map_task1 = {
    "emergency": 0,
    "support offer": 1,
    "neutral": 2
}

id2label_task1 = {v: k for k, v in label_map_task1.items()}

df_unique["label_task1"] = df_unique["auto_label_final"].map(label_map_task1)

In [49]:
label_map_task2 = {
    "informative": 0,
    "personal": 1,
    "other": 2
}

id2label_task2 = {v: k for k, v in label_map_task2.items()}

df_unique["label_task2"] = df_unique["type_of_message_imputed"].map(label_map_task2)

In [50]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df_unique,
    test_size=0.30,
    stratify=df_unique["label_task1"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label_task1"],
    random_state=42
)

In [51]:
from datasets import Dataset

# Task 1 datasets
train_ds1 = Dataset.from_pandas(train_df[["tweet_clean", "label_task1"]])
val_ds1   = Dataset.from_pandas(val_df[["tweet_clean", "label_task1"]])
test_ds1  = Dataset.from_pandas(test_df[["tweet_clean", "label_task1"]])

# Task 2 datasets
train_ds2 = Dataset.from_pandas(train_df[["tweet_clean", "label_task2"]])
val_ds2   = Dataset.from_pandas(val_df[["tweet_clean", "label_task2"]])
test_ds2  = Dataset.from_pandas(test_df[["tweet_clean", "label_task2"]])

In [52]:
from transformers import AutoTokenizer

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Rename function to avoid name conflict
def tokenize_function(batch):
    texts = [str(t) for t in batch["tweet_clean"]]
    
    return tokenizer(
        texts,
        truncation=True,
        padding="max_length",
        max_length=128
    )

# Apply tokenization
train_ds1 = train_ds1.map(tokenize_function, batched=True)
val_ds1   = val_ds1.map(tokenize_function, batched=True)
test_ds1  = test_ds1.map(tokenize_function, batched=True)

train_ds2 = train_ds2.map(tokenize_function, batched=True)
val_ds2   = val_ds2.map(tokenize_function, batched=True)
test_ds2  = test_ds2.map(tokenize_function, batched=True)

Map: 100%|██████████| 2011/2011 [00:00<00:00, 7980.82 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 16262.40 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 15522.59 examples/s]
Map: 100%|██████████| 2011/2011 [00:00<00:00, 16695.46 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 16065.85 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 16148.94 examples/s]

In [53]:
print(train_ds1)

Dataset({
    features: ['tweet_clean', 'label_task1', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2011
})

In [54]:
train_ds1 = train_ds1.rename_column("label_task1", "labels")
val_ds1   = val_ds1.rename_column("label_task1", "labels")
test_ds1  = test_ds1.rename_column("label_task1", "labels")

train_ds2 = train_ds2.rename_column("label_task2", "labels")
val_ds2   = val_ds2.rename_column("label_task2", "labels")
test_ds2  = test_ds2.rename_column("label_task2", "labels")

train_ds1.set_format("torch")
val_ds1.set_format("torch")
test_ds1.set_format("torch")

train_ds2.set_format("torch")
val_ds2.set_format("torch")
test_ds2.set_format("torch")

In [55]:
from transformers import AutoModelForSequenceClassification

model_task1 = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=3,
    id2label=id2label_task1,
    label2id=label_map_task1
)

model_task2 = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=3,
    # id2label=id2label_task2,
    label2id=label_map_task2
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 2855.33it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 3074.35it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [56]:
from sklearn.metrics import accuracy_score, f1_score
import numpy as np

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(labels, preds, average="macro")
    }

In [57]:
from transformers import TrainingArguments
training_args1 = TrainingArguments(
    output_dir="./distilbert_task1",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_steps=100,
    save_steps=500,
report_to=[]
)

In [58]:
from transformers import TrainingArguments
training_args2 = TrainingArguments(
    output_dir="./distilbert_task2",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_steps=100,
    save_steps=500,
    report_to="none"   # FIX HERE
)

In [59]:
from transformers import Trainer
trainer_task1 = Trainer(
    model=model_task1,
    args=training_args1,
    train_dataset=train_ds1,
    eval_dataset=val_ds1,
    compute_metrics=compute_metrics
)

trainer_task1.train()

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.51it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.79it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.53it/s]

TrainOutput(global_step=1260, training_loss=0.2786374909537179, metrics={'train_runtime': 376.6438, 'train_samples_per_second': 53.393, 'train_steps_per_second': 3.345, 'total_flos': 665991723548160.0, 'train_loss': 0.2786374909537179, 'epoch': 10.0})

In [60]:
trainer_task1.evaluate(test_ds1)

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.225143551826477,
 'eval_accuracy': 0.728538283062645,
 'eval_f1_macro': 0.6598423776106611,
 'eval_runtime': 2.4238,
 'eval_samples_per_second': 177.819,
 'eval_steps_per_second': 11.139,
 'epoch': 10.0}

In [61]:
trainer_task1.save_model("./final_model_task1")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.42it/s]

In [62]:
model_task2 = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=3,
    id2label=id2label_task2,
    label2id=label_map_task2,
    problem_type="single_label_classification"
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 2075.10it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [63]:
trainer_task2 = Trainer(
    model=model_task2,
    args=training_args2,
    train_dataset=train_ds2,
    eval_dataset=val_ds2,
    compute_metrics=compute_metrics
)

trainer_task2.train()

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.91it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  5.06it/s]

TrainOutput(global_step=1260, training_loss=0.414835392482697, metrics={'train_runtime': 369.2719, 'train_samples_per_second': 54.459, 'train_steps_per_second': 3.412, 'total_flos': 665991723548160.0, 'train_loss': 0.414835392482697, 'epoch': 10.0})

In [64]:
print("Task-2 Test Results")
trainer_task2.evaluate(test_ds2)

Task-2 Test Results

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.4548428058624268,
 'eval_accuracy': 0.6194895591647331,
 'eval_f1_macro': 0.6134523099958249,
 'eval_runtime': 2.3411,
 'eval_samples_per_second': 184.1,
 'eval_steps_per_second': 11.533,
 'epoch': 10.0}

In [65]:
trainer_task2.save_model("./final_message_type_model")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  6.41it/s]

In [66]:
# BERT 

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

In [67]:

#  Clean text columns first 
train_df["tweet_clean"] = train_df["tweet_clean"].fillna("").astype(str)
val_df["tweet_clean"]   = val_df["tweet_clean"].fillna("").astype(str)
test_df["tweet_clean"]  = test_df["tweet_clean"].fillna("").astype(str)

In [68]:
# Build HuggingFace datasets 
train_ds = Dataset.from_pandas(train_df[["tweet_clean", "label_task1"]])
val_ds   = Dataset.from_pandas(val_df[["tweet_clean", "label_task1"]])
test_ds  = Dataset.from_pandas(test_df[["tweet_clean", "label_task1"]])

In [69]:
# Build HuggingFace datasets
train_ds = Dataset.from_pandas(train_df[["tweet_clean", "label_task1"]])
val_ds   = Dataset.from_pandas(val_df[["tweet_clean", "label_task1"]])
test_ds  = Dataset.from_pandas(test_df[["tweet_clean", "label_task1"]])

In [70]:
# Load tokenizer 
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    texts = [str(x) for x in batch["tweet_clean"]]
    return tokenizer(
        texts,
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_ds = train_ds.map(tokenize, batched=True)
val_ds   = val_ds.map(tokenize, batched=True)
test_ds  = test_ds.map(tokenize, batched=True)

Map: 100%|██████████| 2011/2011 [00:00<00:00, 12662.22 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 15497.97 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 15785.27 examples/s]

In [71]:
# Rename label column 
train_ds = train_ds.rename_column("label_task1", "labels")
val_ds   = val_ds.rename_column("label_task1", "labels")
test_ds  = test_ds.rename_column("label_task1", "labels")

train_ds.set_format("torch")
val_ds.set_format("torch")
test_ds.set_format("torch")

In [72]:

# Load model 
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2748.70it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [73]:

#  Metrics 
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(labels, preds, average="macro")
    }

In [74]:


# Training arguments 
training_args = TrainingArguments(
    output_dir="./bert_task1",
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    report_to="none"
)

In [75]:

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.90it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

TrainOutput(global_step=1260, training_loss=0.2453043264056009, metrics={'train_runtime': 726.2522, 'train_samples_per_second': 27.69, 'train_steps_per_second': 1.735, 'total_flos': 1322802707627520.0, 'train_loss': 0.2453043264056009, 'epoch': 10.0})

In [76]:

print("Test Results:")
print(trainer.evaluate(test_ds))

Test Results:

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.769580364227295, 'eval_accuracy': 0.7331786542923434, 'eval_f1_macro': 0.6696780369860885, 'eval_runtime': 4.5399, 'eval_samples_per_second': 94.937, 'eval_steps_per_second': 5.947, 'epoch': 10.0}

In [77]:
# Convert Task 2 labels to integers

from sklearn.preprocessing import LabelEncoder

le_task2 = LabelEncoder()

train_df["label_task2"] = le_task2.fit_transform(train_df["label_task2"])
val_df["label_task2"]   = le_task2.transform(val_df["label_task2"])
test_df["label_task2"]  = le_task2.transform(test_df["label_task2"])

print("Task 2 classes:", le_task2.classes_)

Task 2 classes: [ 0.  1.  2. nan]

In [78]:
# Build datasets using Task 2 labels

train_ds = Dataset.from_pandas(train_df[["tweet_clean", "label_task2"]])
val_ds   = Dataset.from_pandas(val_df[["tweet_clean", "label_task2"]])
test_ds  = Dataset.from_pandas(test_df[["tweet_clean", "label_task2"]])

In [79]:
# Convert text into tokens for BERT

train_ds = train_ds.map(tokenize, batched=True)
val_ds   = val_ds.map(tokenize, batched=True)
test_ds  = test_ds.map(tokenize, batched=True)

Map: 100%|██████████| 2011/2011 [00:00<00:00, 12984.94 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 15713.92 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 15846.15 examples/s]

In [80]:
# Rename label column to what Trainer expects

train_ds = train_ds.rename_column("label_task2", "labels")
val_ds   = val_ds.rename_column("label_task2", "labels")
test_ds  = test_ds.rename_column("label_task2", "labels")

train_ds.set_format("torch")
val_ds.set_format("torch")
test_ds.set_format("torch")

In [81]:
# Detect number of classes automatically

num_classes = len(train_df["label_task2"].unique())

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=num_classes
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2796.94it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [100]:
# Basic training setup

training_args = TrainingArguments(
    output_dir="./bert_task2",
    num_train_epochs=10,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    report_to="none"
)

In [ ]:
# Train model

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.98it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

In [84]:
print("Test Results:")
print(trainer.evaluate(test_ds))

Test Results:

/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 2.6362926959991455, 'eval_accuracy': 0.6450116009280742, 'eval_f1_macro': 0.6385402305428527, 'eval_runtime': 4.4453, 'eval_samples_per_second': 96.957, 'eval_steps_per_second': 6.074, 'epoch': 15.0}

In [85]:
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(labels, preds, average="macro")
    }

In [86]:
# Task 1 dataset (emergency classification)

train_ds1 = Dataset.from_pandas(train_df[["tweet_clean", "label_task1"]])
val_ds1   = Dataset.from_pandas(val_df[["tweet_clean", "label_task1"]])
test_ds1  = Dataset.from_pandas(test_df[["tweet_clean", "label_task1"]])

In [87]:
# Load RoBERTa tokenizer

roberta_tok = AutoTokenizer.from_pretrained("roberta-base")

def tokenize_task1(batch):
    return roberta_tok(
        batch["tweet_clean"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_ds1 = train_ds1.map(tokenize_task1, batched=True)
val_ds1   = val_ds1.map(tokenize_task1, batched=True)
test_ds1  = test_ds1.map(tokenize_task1, batched=True)

Map: 100%|██████████| 2011/2011 [00:00<00:00, 16550.33 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 17984.65 examples/s]
Map: 100%|██████████| 431/431 [00:00<00:00, 17424.72 examples/s]

In [88]:
# Trainer expects column name "labels"

train_ds1 = train_ds1.rename_column("label_task1", "labels")
val_ds1   = val_ds1.rename_column("label_task1", "labels")
test_ds1  = test_ds1.rename_column("label_task1", "labels")

train_ds1.set_format("torch")
val_ds1.set_format("torch")
test_ds1.set_format("torch")

In [89]:
# 3 classes for Task 1

model_task1 = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=3
)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2864.99it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.dense.weight         | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [95]:
training_args1 = TrainingArguments(
    output_dir="./roberta_task1",
    num_train_epochs=10,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    report_to="none"
)

In [96]:
trainer_task1 = Trainer(
    model=model_task1,
    args=training_args1,
    train_dataset=train_ds1,
    eval_dataset=val_ds1,
    compute_metrics=compute_metrics
)

trainer_task1.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.20s/it]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.43it/s]
/Users/munakandel/Desktop/community resiliance/hurricane_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.15it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s]

TrainOutput(global_step=2520, training_loss=0.2628566153110966, metrics={'train_runtime': 952.8126, 'train_samples_per_second': 21.106, 'train_steps_per_second': 2.645, 'total_flos': 1322802707627520.0, 'train_loss': 0.2628566153110966, 'epoch': 10.0})

In [ ]:
print("Test Results:")
print(trainer.evaluate(test_ds1))